# Generated by Django 5.2.9 on 2026-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created_at'], 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
